import p1 from "../../assets/1.png"
import p2 from "../../assets/2.png"
import p3 from "../../assets/3.png"
import p4 from "../../assets/4.png"
import p5 from "../../assets/5.png"
import p6 from "../../assets/6.png"
import p7 from "../../assets/7.png"
import p8 from "../../assets/8.png"
import p9 from "../../assets/9.png"
import p10 from "../../assets/10.png"
import p11 from "../../assets/11.png"
import p12 from "../../assets/12.png"
import p13 from "../../assets/13.png"
import friends from "../../assets/friend.png"
import img from "../../assets/img.png"
import map from "../../assets/map.png"
export const photos = {p1, p2, p3, p4, p5, p6, p7, p8,p9, p10, p11, p12, p13, friends, img, map}
